# process data generated by tree-zig-zag/Metropolis/Finite_sites/gen_data to
# expand repeated rows and drop multiplicity column

library("dplyr")
library("readr")

# each row is a sequence at one or more taxa, last column records multiplicity
fs_raw <- read_delim(
    file.path("finitesites-raw.dat"),
    delim = " ",
    col_names = FALSE,
    col_types = cols(.default = "i")
)
m_col <- pull(fs_raw, -1)

# shuffle row indices and drop multiplicity column
m_inds <- rep.int(seq_along(m_col), m_col)
n_inds <- sample(m_inds)

fs_shf <- fs_raw |>
    slice(n_inds) |>
    select(-last_col())

write_delim(fs_shf, "finitesites.dat", delim = " ", col_names = FALSE)
